/**
 * Generated by Gas3 v1.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.baidu.ite.mrbs.entity {

    [Bindable]
    [RemoteClass(alias="com.baidu.ite.mrbs.entity.MrbsArea")]
    public class MrbsArea extends MrbsAreaBase {
    }
}