/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (RoomSearchBean.as).
 */

package com.baidu.ite.mrbs.entity.util {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class RoomSearchBeanBase implements IExternalizable {

        private var _areaList:ListCollectionView;
        private var _beiginHour:int;
        private var _beiginMimi:int;
        private var _capacity:int;
        private var _endDate:Date;
        private var _isMust:int;
        private var _startDate:Date;
        private var _timeConsuming:Number;

        public function set areaList(value:ListCollectionView):void {
            _areaList = value;
        }
        public function get areaList():ListCollectionView {
            return _areaList;
        }

        public function set beiginHour(value:int):void {
            _beiginHour = value;
        }
        public function get beiginHour():int {
            return _beiginHour;
        }

        public function set beiginMimi(value:int):void {
            _beiginMimi = value;
        }
        public function get beiginMimi():int {
            return _beiginMimi;
        }

        public function set capacity(value:int):void {
            _capacity = value;
        }
        public function get capacity():int {
            return _capacity;
        }

        public function set endDate(value:Date):void {
            _endDate = value;
        }
        public function get endDate():Date {
            return _endDate;
        }

        public function set isMust(value:int):void {
            _isMust = value;
        }
        public function get isMust():int {
            return _isMust;
        }

        public function set startDate(value:Date):void {
            _startDate = value;
        }
        public function get startDate():Date {
            return _startDate;
        }

        public function set timeConsuming(value:Number):void {
            _timeConsuming = value;
        }
        public function get timeConsuming():Number {
            return _timeConsuming;
        }

        public function readExternal(input:IDataInput):void {
            _areaList = input.readObject() as ListCollectionView;
            _beiginHour = input.readObject() as int;
            _beiginMimi = input.readObject() as int;
            _capacity = input.readObject() as int;
            _endDate = input.readObject() as Date;
            _isMust = input.readObject() as int;
            _startDate = input.readObject() as Date;
            _timeConsuming = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_areaList);
            output.writeObject(_beiginHour);
            output.writeObject(_beiginMimi);
            output.writeObject(_capacity);
            output.writeObject(_endDate);
            output.writeObject(_isMust);
            output.writeObject(_startDate);
            output.writeObject(_timeConsuming);
        }
    }
}